UI/Areas/Admin/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataAccess;
using Microsoft.AspNetCore.Mvc;
using UI.Models;
using Models;

namespace UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProjectController : Controller
    {
        private readonly IEFRepository _repository;

        public ProjectController(IEFRepository repository)
        {
            _repository = repository;
        }
       
        public IActionResult Index()
        {
            ViewBag.PageName = "Project List";
            
            return View();
        }

        [HttpGet]
        public IActionResult GetProjects()
        {
            return ViewComponent("UI.ViewComponents.ProjectList");
        }

        #region ProjectCreate
        [HttpGet]
        public IActionResult _Create()
        {
            return PartialView();
        }
        [HttpPost]
        public IActionResult _Create(ProjectViewModel model)
        {
            bool Status = false;
            string Message = string.Empty;
            if (ModelState.IsValid)
            {
                _repository.Add(new Project()
                {
                    Code = model.Code,
                    ProjectName = model.ProjectName
                });
                if (_repository.SaveChanges())
                {
                    Status = true;
                    Message = "Records Sucessfully Added.";
                }
                else
                {
                    Status = false;
                    Message = "Error creating record";
                }
            }
            else
            {
                ModelState.AddModelError("", "Provide all valid data to proceed");
            }
            return Json(new { status = Status, message = Message });
        }
        #endregion

        #region Project Edit
        [HttpGet]
        public IActionResult _Edit(int id)
        {
            var entry = _repository.GetProject(id);
            if (entry == null)
            {
                return NotFound();
            }

            var model = new ProjectViewModel()
            {
              ProjectId=entry.ProjectId,
               Code=entry.Code,
               ProjectName=entry.ProjectName
            };

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult _Edit(ProjectViewModel model)
        {
            bool Status = false;
            string Message = string.Empty;
            if (ModelState.IsValid)
            {
                var result = _repository.GetProject(model.ProjectId);
                if (result != null)
                {
                    result.Code = model.Code;
                    result.ProjectName = model.ProjectName;
                    _repository.Update(result);
                    if (_repository.SaveChanges())
                    {
                        Status = true;
                        Message = "Record Update Successfully ";
                        ViewBag.Message = "Successfully Update Recourd";
                    }
                }
            }
            else
            {
                Message = "Error :Please Provide All Required Fields. ";
                ModelState.AddModelError("", "Error ! Please Provide All Required Fields.");
            }
            return Json(new { status = Status, message = Message });
        }
        #endregion

        #region Delete Project

        public ActionResult Delete(int Id)
        {
            bool Status = false;
            string Message = string.Empty;
            var project = _repository.GetProject(Id);
           _repository.Delete(project);
            _repository.Update(project);

            if (_repository.SaveChanges())
            {
                Status = true;
                Message = "Project Delete Successfully.";
            }
            return Json(new { status = Status, message = Message });
        }

        #endregion

    }
}

UI/Controllers/DashBoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace UI.Controllers
{
    public class DashBoardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

    }
}

UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    @* Main Layout *@
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Procurement System</title>
    <link href="~/lib/bootswatch/dist/yeti/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/Font-Awesome/css/all.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles",required:false)
    <environment include="Development">

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" asp-area="" asp-controller="DashBoard" asp-action="Index">Procurement System</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-area="Admin" asp-controller="Project" asp-action="Index">Admin</a>
                    </li>
                }

                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contact">Contact Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">About Us</a>
                </li>
            </ul>

            <ul class="navbar-nav float-right">
                @if (!User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Auth" asp-action="SignIn">
                            <i class="fa fa-sign-in-alt"></i>
                            Sign In
                        </a>
                    </li>
                }
                else
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle"
                           href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Welcome @User.Identity.Name!
                        </a>
                        @*<div class="dropdown-menu mt-2" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-area="" asp-controller="User" asp-action="Index" asp-route-Username="@User.Identity.Name">Profile</a>
                            <div class="dropdown-divider"></div>
                           
                        </div>*@

                   
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link" asp-area="" asp-controller="Auth" asp-action="SignOut">Sign Out</a>
                    </li>
                }
            </ul>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        @*<hr />
        <footer class="navbar-expand navbar-fixed-bottom">
            <p>&copy; 2019 - UI</p>
        </footer>*@
    </div>
    
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <div class="loading-bar"></div>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/Font-Awesome/js/all.js"></script>

    <script>
        $(function () {
            $(document).bind('ajaxStart', function () {
                $("body").addClass('loading');
            }).bind('ajaxStop', function () {
                $("body").removeClass('loading');
            });
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>

</html>